apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-pvc-1
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2G
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-pvc-2
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2G
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-pvc-3
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2G