kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4 
nodes:
- role: control-plane
- role: worker
  extraMounts:
    - hostPath: ../volumes/jenkins
      containerPath: /usr/jenkins
    - hostPath: ../volumes/gitlab/config
      containerPath: /usr/gitlab/config 
    - hostPath: ../volumes/gitlab/logs
      containerPath: /usr/gitlab/logs 
    - hostPath: ../volumes/gitlab/data
      containerPath: /usr/gitlab/data
  extraPortMappings:
    - containerPort: 80
      hostPort: 80
    - containerPort: 443
      hostPort: 443