apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gitlab
  name: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gitlab
    spec:
      containers:
      - image: gitlab/gitlab-ce
        name: gitlab-ce
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 22
        env:
        - name: GITLAB_OMNIBUS_CONFIG
          value: external_url 'http://gitlab.172.18.0.3.nip.io'
        volumeMounts:
          - name: gitlab-pv-config 
            mountPath: "/etc/gitlab"
          - name: gitlab-pv-logs 
            mountPath: "/var/log/gitlab"
          - name: gitlab-pv-config 
            mountPath: "/var/opt/gitlab"
        resources: {}
      volumes:
      - name: gitlab-pv-config
        hostPath:
          path: "/usr/gitlab/config"
          type: Directory
      - name: gitlab-pv-logs
        hostPath:
          path: "/usr/gitlab/logs"
          type: Directory
      - name: gitlab-pv-data
        hostPath:
          path: "/usr/gitlab/data"
          type: Directory