apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: gitlab 
  name: gitlab 
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: gitlab
status:
  loadBalancer: {}