apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: jenkins
rules:
- apiGroups:
  - ""
  - metrics.k8s.io
  - extensions
  - apps
  resources:
  - pods
  - pods/log
  - events
  - pods/exec
  verbs:
  - create
  - delete
  - list
  - get
  - watch