apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: jenkins
  name: jenkins
spec:
  ports:
  - name: http 
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: jenkins
status:
  loadBalancer: {}
